# python dict to map special characters to string description

characters = {
    # ' ': 'space',
    '(': 'leftparenthesis',
    ')': 'rightparenthesis',
    '[': 'leftsquarebracket',
    ']': 'rightsquarebracket',
    '{': 'leftcurlybrace',
    '}': 'rightcurlybrace',
    ',': 'comma',
    '.': 'period',
    ';': 'semicolon',
    ':': 'colon',
    '?': 'questionmark',
    '!': 'exclamationmark',
    '"': 'doublequote',
    "'": 'singlequote',
    '/': 'forwardslash',
    '\\': 'backslash',
    '|': 'pipe',
    '@': 'atsign',
    '#': 'hashtag',
    '$': 'dollarsign',
    '%': 'percentsign',
    '^': 'caret',
    '&': 'ampersand',
    '*': 'asterisk',
    '-': 'hyphen',
    '_': 'underscore',
    '+': 'plussign',
    '=': 'equalssign',
    '<': 'leftanglebracket',
    '>': 'rightanglebracket',
    '`': 'backtick',
    '~': 'tilde',
}